# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "@maxandersen"
email: website@xam.dk
description: >- # this means to ignore newlines until "baseurl:"
             Welcome
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xam.dk" # the base hostname & protocol for your site, e.g. http://example.com
author: maxandersen
full_name: Max Rydahl Andersen

permalink: "/blog/:categories/:title/"

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog 
plugins:
  - jekyll-feed

blog_path: "/blog"

paginate: 10
paginate_path: "/blog/page:num/"


# liquid:
 # strict_variables: true
 # strict_filters: true

asciidoctor:
  attributes:
    hardbreaks: "@"
    source-highlighter: pygments
    pygments-stylesheet: assets/asciidoc-pygments.css
    pygments-css: class
    pygments-linenums-mode: table
    pygments-style: perldoc

    icons: font
    

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      background: "/img/post-bg.jpg"

webmentions:
  username: xam.dk
  html_proofer: true
  cache_folder: _data/webmentions
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    #reposts: _includes/webmentions/reposts.html
    #webmentions: _includes/webmentions/webmentions.html
  legacy_domains:
    - http://xam.dk
    # debug: true
  js: false
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: every 2 weeks

feed:
  path: ./blog/feed.atom


jekyll_analytics:
    GoogleAnalytics:
      id: UA-70032-1
      anonymizeIp: false

comments:
  disqus:
    short_name: blogxamdk
    api_key: PuDlF1o1zdjP9hll5fhfP53UgojHZNIjkZktEMgoEBWWpvl0ttXWgZIe5Lj9AJ8t

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - ".#*"
   - Rakefile
   - config.toml

include:
  - maxandersen/.well-known/atproto-did
  

