---
title: About me
description: This is what I do.
background: /img/about-bg.jpg
---

== Danish guy enjoying working on open source software.

Making things happen at Red Hat - though at the moment (Aug. 2018-2019) on a sabbatical.

I worked as manager and technical lead of https://openshift.io[OpenShift.io] and before that http://tools.jboss.org[JBoss Tools] and http://devstudio.redhat.com[JBoss Developer Studio]. 

I co-host http://asylum.jboss.org[JBoss Asylum] podcast.

I was on the http://eclipse.org[Eclipse board]. 

I got an http://update.xam.dk[Eclipse Updatesite]

I use this website to mainly blog about things that does not fit into Red Hat related blogs.

I tweet too much about email clients!

=== Contact

* Twitter: link:https://twitter.com/maxandersen[@maxandersen]
* Github: link:https://github.com/maxandersen[maxandersen]
* Freenode irc: maxandersen
* Skype: link:callto://max.rydahl.andersen[max.rydahl.andersen]
* personal e-mail: max@xam.dk
* work e-mail: manderse@redhat.com


=== Acknowledgements

[%hardbreaks]
This site is built with https://jekyllrb.com[Jekyll].
The style is derived from Apache Source Licensed http://startbootstrap.com/template-overviews/clean-blog/[Clean Blog] by startbootstrap.com.
The http://www.inspiringwallpapers.net/superman-logo-dirty.html[Dirty Superman] logo is by Paul Mood.
http://unrealdrw0w.deviantart.com/art/Thinking-chimp-310774912["Thinking chimp"] by uNrealDrw0w.

Any examples, source, tips, tricks, etc. you find on this page written by me you are free to use.

