---
title: House
author: Max Rydahl Andersen
background: /images/house.jpg
---

= Hyggelig og idylisk Hus/Gård søges!

Vi er en familie på fire med to børn på 4 og 7 år. Vi har boet i Schweiz I ca. 17 år siden 2004 og har nu besluttet os for at flytte tilbage.

Derfor leder vi efter et hus/ejendom på Fyn, Danmark. 

Foto er originalt fra realmaeglerne.dk

Nedenstående er vores tanker om hvad der er vigtigt om vores fremtidige hus.

== Huset

Tilbagetrukket/beskyttet fra vej, Mindst ~250 kvm beboelse.

Mulighed for stort køkken alrum

Gerne kontor/teenage afdeling

Gerne med ekstra plads feks Bed & Breakfast

Have sjæl og charme

Være i rimelig stand eller muligt at fixe

== Jord 

Vi er ikke landmaend, men vil gerne have nok jord med plads til

- Have
- Hestefolde (2 til 4 heste)
- Ridebane

Mere end 2 hektar er okey, evt. med forpagtning for områder udover hvad vi skal bruge.

== Beliggenhed

Gerne i udkant eller tæt på mindre by med godt sammenhold.

Let adgang til skov og natur uden tung trafik.

Strand 3-10 km

Der skal være noget at se på, ikke flade marker uden bevoksning.

== Have 

Have med store gamle træer

Hyggekroge

== Udbygninger

- Stald til heste et plus, men planlagt losdrift.
- Værksted
- Gildesal
- Maskinhus, stor nok til at kunne bruges som lille ridehus

== Vi ønsker ikke

- Beliggenhed lige ved stor vej
- Stråtag 
- Stor sø tæt på

== Kontakt 

Send mail til house@xam.dk eller giv et ring på link:tel:0041795978842[+41 79 597 88 42] (indtal en besked hvis vi ikke tager den).
