---
title: About me
subtitle: This is what I do.
banner: /img/about-bg.jpg
---

== Danish guy enjoying working on open source software.

Making things happen at Red Hat. 

I currently work as technical lead of http://tools.jboss.org[JBoss Tools] and http://devstudio.redhat.com[JBoss Developer Studio]. 

I co-host http://asylum.jboss.org[JBoss Asylum] podcast.

I'm on the http://eclipse.org[Eclipse board]. 

I got an http://update.xam.dk[Eclipse Updatesite]

I use this website to mainly blog about things that does not fit into
the http://tools.jboss.org/blog[JBoss Tools blog] 

I tweet too much about email clients!

=== Contact

* Twitter: link:https://twitter.com/maxandersen[@maxandersen]
* Github: link:https://github.com/maxandersen[maxandersen]
* Freenode irc: maxandersen
* Skype: link:callto://max.rydahl.andersen[max.rydahl.andersen]
* e-mail: manderse@redhat.com

=== Acknowledgements

This site is built with http://awestruct.org[Awestruct].
The style is derived from Apache Source Licensed http://startbootstrap.com/template-overviews/clean-blog/[Clean Blog] by startbootstrap.com.
The http://www.inspiringwallpapers.net/superman-logo-dirty.html[Dirty Superman] logo is by Paul Mood.
http://unrealdrw0w.deviantart.com/art/Thinking-chimp-310774912["Thinking chimp"] by uNrealDrw0w.

Any examples, source, tips, tricks, etc. you find on this page written by me you are free to use.

