= You do not have to find out you are dying to start living

:page-layout: post
:page-background: /img/clouds-bg.jpg

At breakfast this morning I was https://www.reddit.com/r/videos/comments/b73g9q/in_2012_a_young_man_called_zach_sobiech_who_was/[reminded] about https://en.wikipedia.org/wiki/Zach_Sobiech[Zach Sobiech] who was at 14 diagnosed with https://en.wikipedia.org/wiki/Osteosarcoma[osteosarcoma] and at age 17 he knew he was dying and he made a song called 'Clouds'.

video::sDC97j6lfyc[youtube, width=640, height=480]

A song to say goodbye and to remind people that:

[quote, Zach Sobiech]
You don't have to find out you are dying to start living.

The song went viral and around the world spreading the word and
generated a good chunk of donations to cancer treatment.

Before he died a bunch of artists and celebrities around the world
made a tribute to him.

video::7zxXAtmmLLc[youtube, width=640, height=480]

Since then there are https://www.google.ch/search?q=zach+sobiech+choir[regular big choirs] doing a variation of the
Clouds song, incl. this massive 5000 people choir:

video::bLhUS_QjcZY[youtube, width=640, height=480]

Not sure why, but this story just hit me today and I wanted to take
out a few minutes of my day to share this message in hope it
might ring home with others.

Yes - You don't have to find out you are dying to start living.

Today I'm going on boat with my 5 year old kid.

What are you doing to live a little today ?

/max
