name: publish-to-xam.dk

on:
  push: 
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-publish
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install-commands
        run: |
          sudo apt-get install -qq sshpass
      - uses: actions/cache@v1
        id: cache-jekyll
        with:
          path: .jekyll-cache
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: build-and-publish
        env:
          XAMSSH: "${{ secrets.XAMSSH }}"
        run: bundle exec rake travis
        